### ISSUE TITLE
Request: Use refHead by default

### ISSUE THREAD

**Issue by jlefebvre1997** [CircleCI-Public/trigger-circleci-pipeline-action#29]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

When merging a PR, `$GITHUB_REF` contains the name of the target branch, not source branch, which can create inconsistency. 

### Describe the solution you'd like

It should be alright to use `$GITHUB_HEAD_REF` by default, if it is present of course. As the Github Actions documentation states : 
```
GITHUB_HEAD_REF : The head ref  or source branch of the pull request in a workflow run. This property is  only set when the event that triggers a workflow run is either pull_request or pull_request_target. For example, feature-branch-1.
```
It seems to be a more reliable way of checking if we're in a PR than checking if `$GITHUB_REF` starts with `refs/pull/...` 

### Teachability, documentation, adoption, migration strategy

This will be the default behavior, so it should be stated in the doc, but no or almost no changes for the users since it covers only the case of merging a Pull Request

### What is the motivation / use case for changing the behavior?

When you plug an action to the `pull_request closed` event, you expect the instructions to run on the source branch when your PR is closed, including when it's closed by merging the source branch. 
The exemple in my case was the destruction of an ephemeral environment, based on the branch the PR is based on. So, when merging the branch, the destroyed environment is the one corresponding to the source branch (`main`, for example), which shouldn't be destroyed. 

Also, I think it's not right to have such an inconsistency in the different behaviors (which is mostly caused by github actions, I agree on this).

**Comment by jlefebvre1997** [comment]
If you think this is a good idea I can take care of it

**Comment by KyleTryon** [comment]
Apologies again for not seeing this earlier. The fix should be included here: https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/releases/tag/v1.0.6

Please let me know if you have any issues.
