### ISSUE TITLE
Bug: No CCI_HOST Causes Error

### ISSUE THREAD

**Issue by whatisdot** [CircleCI-Public/trigger-circleci-pipeline-action#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

#42 introduced an environment variable `CCI_HOST` that can be used to change the hostname for requests to something other than `circleci.com`.

After attempting to use the latest version of the action, we encounter an error if `CCI_HOST` is not defined as an `env` in the action:
> Preparing CircleCI Pipeline Trigger
  Org: [REDACTED]
  Repo: [REDACTED]
  Triggering CircleCI Pipeline for [REDACTED]
  Triggering URL: https://**undefined**/api/v2/project/gh/[REDACTED]/[REDACTED]/pipeline
  Triggering branch: main
  Parameters:
  {"GHA_Actor":"whatisdot","GHA_Action":"run-deployment-steps","GHA_Event":"workflow_dispatch","GHA_Meta":"qa1"}
Failed to trigger CircleCI Pipeline
  **Error: Error: getaddrinfo EAI_AGAIN undefined**
  **Error: getaddrinfo EAI_AGAIN undefined**

### Minimum reproduction code

(no changes required)

### Steps to reproduce

1. Update the GitHub Action reference to the `main` branch
2. Trigger a build that uses the action

### Expected behavior

The action should default to using `circleci.com` for the API host name.

### GitHub Action Version

`main` branch

**Comment by whatisdot** [comment]
@KyleTryon I've spotted an issue on the `main` branch related to a recent merge. Would this project be open to switching to TypeScript? The language makes it easier to spot potential problems and to write Jest test cases that would catch issues like this ([working example](https://github.com/CircleCI-Public/trigger-circleci-pipeline-action/compare/main...snapsheet:trigger-circleci-pipeline-action:fix-host-undefined-error?expand=1)).

**Comment by KyleTryon** [comment]
> Would this project be open to switching to TypeScript? 

Enthusiastically, and professionally, Hell ya!

I would be happy to convert us to TypeScript. I may even be able to today. Good suggestion 👍

**Comment by whatisdot** [comment]
If you do have time to submit this change, we will gladly test and review it.

**Comment by whatisdot** [comment]
This was resolve in #51
